Changed installing method Changed messages

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,7 +2,7 @@
 
 DW_VERSION="2019.3.22"
 
-trap "./remove -s; exit" SIGINT
+trap './remove -s;echo "Stopped, Removing any half installed files...";exit' SIGINT
 
 if [ "$(id -u)" -ne 0 ]; then
   echo "This script must be run as root. Enter your password...";
@@ -27,7 +27,7 @@ fi
 
 echo -e "\e[00;32m[1/5] Setting Permissions...\e[00m"
 DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
-cd $DIR || { echo "Error, exiting..."; exit; }
+cd "$DIR" || { echo "Error, exiting..."; exit; }
 chmod a+x ./remove
 chmod a+x ./lib/systemd/system-sleep/dynamicwall.sh
 chmod +x ./bin/dynamic-wall/dynamicwall
@@ -64,38 +64,28 @@ function install_files(){
 
       install -o "$usrnm" -g "$usrnm" -d $1
       install -o "$usrnm" -g "$usrnm" -D $DIR$1/* $1
-    elif [ "$3" = "hidden" ]; then
+    elif [ "$2" != "" ]; then
       echo "installing: $1"
 
-      install -o "$usrnm" -g "$usrnm" -d /home/$2/.$1
-      install -o "$usrnm" -g "$usrnm" -D $DIR/$1/* /home/$2/.$1
-    elif [[ $2 = "usr" ]]; then
-      echo "installing: $1"
-
-      install -o "$usrnm" -g "$usrnm" -d usr/$1
-      install -o "$usrnm" -g "$usrnm" -D $DIR$1/* usr/$1
-    else
-      echo "installing: $1"
-
-      install -o "$usrnm" -g "$usrnm" -d /home/$2/$1
-      install -o "$usrnm" -g "$usrnm" -D $DIR$1/* /home/$2/$1
+      install -o "$usrnm" -g "$usrnm" -d $2$1
+      install -o "$usrnm" -g "$usrnm" -D $DIR/$1/* $2$1
     fi
 }
 
-install_files "/bin" "$usrnm"
-install_files "/bin/dynamic-wall" "$usrnm"
+install_files "/bin" "/home/$usrnm"
+install_files "/bin/dynamic-wall" "/home/$usrnm"
 cp -pR $DIR/bin/dynamic-wall/oldvar /home/"$usrnm"/bin/dynamic-wall/.oldvar
-install_files "/bin/dynamic-wall/themes" "$usrnm"
-install_files "/bin/dynamic-wall/themes/EarthView" "$usrnm"
-install_files "/bin/dynamic-wall/themes/mojave_dynamic" "$usrnm"
-install_files "/bin/dynamic-wall/themes/NewOrleans" "$usrnm"
+install_files "/bin/dynamic-wall/themes" "/home/$usrnm"
+install_files "/bin/dynamic-wall/themes/EarthView" "/home/$usrnm"
+install_files "/bin/dynamic-wall/themes/mojave_dynamic" "/home/$usrnm"
+install_files "/bin/dynamic-wall/themes/NewOrleans" "/home/$usrnm"
 
 if [[ $method = "--cron" ]]; then
   echo -e "\e[00;32m\nSkipping systemd files due to --cron installation...\e[00m"
 else
   echo -e "\e[00;32m\nInstalling systemd units...\e[00m"
-  install_files "config/systemd/user" "$usrnm" "hidden"
-  install_files "config/systemd/user/dynamicwall.timer.d" "$usrnm" "hidden"
+  install_files "config/systemd/user" "/home/$usrnm/."
+  install_files "config/systemd/user/dynamicwall.timer.d" "/home/$usrnm/."
 fi
 
 while true; do
@@ -106,7 +96,7 @@ while true; do
       if  [[ -d /lib/systemd ]]; then
         install_files "/lib/systemd/system-sleep"
       elif [[ -d /usr/lib/systemd ]]; then
-        install_files "/lib/systemd/system-sleep" usr
+        install_files "/lib/systemd/system-sleep" "usr/"
       else
         echo -e "\e[00;31mCan't find system-sleep directory, skipping...\e[00m"
       fi
@@ -128,12 +118,14 @@ done
 
 echo -e "\e[00;32m\n[5/5] Creating software links...\e[00m"
 ln -s -f /home/"$usrnm"/bin/dynamic-wall/dynamicwall /usr/local/bin/dynamicwall
+echo "Created symlink /usr/local/bin/dynamicwall → /home/$usrnm/bin/dynamic-wall/dynamicwall"
 
 if [ -f /bin/systemctl ] && ! [[ $method = "--cron" ]]; then
-	echo -e "\n\033[0;33mEnabling and starting systemd...\033[0m"
-    ln -s -f /home/"$usrnm"/.config/systemd/user/dynamicwall.timer.d/ /etc/systemd/system/
-    systemctl enable /home/"$usrnm"/.config/systemd/user/dynamicwall.service /home/"$usrnm"/.config/systemd/user/dynamicwall.timer
-    systemctl start dynamicwall.timer
+  ln -s -f /home/"$usrnm"/.config/systemd/user/dynamicwall.timer.d/ /etc/systemd/system/
+  echo "Created symlink /etc/systemd/system/dynamicwall.timer.d → /home/$usrnm/.config/systemd/user/dynamicwall.timer.d."
+  systemctl enable /home/"$usrnm"/.config/systemd/user/dynamicwall.service /home/"$usrnm"/.config/systemd/user/dynamicwall.timer
+  echo -e "\n\033[0;33mEnabling and starting systemd...\033[0m"
+  systemctl start dynamicwall.timer
 else
 	echo -e "\n\033[0;33mCreating cronjob...\033[0m"
   crontab -u $usrnm -l | { cat; echo "*/45 * * * * /home/$usrnm/bin/dynamic-wall/dynamicwall"; } | crontab -u $usrnm -
