Reimplemented error message if config files are missing, correctly

diff --git a/bin/dynamic-wall/dynamic b/bin/dynamic-wall/dynamic
--- a/bin/dynamic-wall/dynamic
+++ b/bin/dynamic-wall/dynamic
@@ -6,8 +6,7 @@ usrnm=$(grep -i ':x:1000:' -A 0 /etc/passwd | sed 's/:x:1000:.*//')
 date=$(date +%H | sed 's/\<0//g')
 # shellcheck source=/dev/null
 # Source Config File
-. /home/"$usrnm"/bin/dynamic-wall/dynamicwall.config
-#|| echo "Can't find user config, loading defaults..."; . /home/"$usrnm"/bin/dynamic-wall/default.config || echo "Can't find user config or default config, exiting..."; exit
+. /home/"$usrnm"/bin/dynamic-wall/dynamicwall.config || . /home/"$usrnm"/bin/dynamic-wall/default.config || exit; echo "can't find config files, exiting..."
 
 function main_script() {
 	if [[ "$date" -le "4" ]]; then
