Formatting

diff --git a/bin/dynamic-wall/dynamicwall b/bin/dynamic-wall/dynamicwall
--- a/bin/dynamic-wall/dynamicwall
+++ b/bin/dynamic-wall/dynamicwall
@@ -66,7 +66,7 @@ function set_wallpaper() {
 	full_image_path=$(realpath "$1")
 	#Run process as currently logged in user, export display and DBUS session, and then evaluate wallpaper script, needed for automatic updating
 	sudo -u "$usrnm" \
-  XDG_RUNTIME_DIR=/run/user/1000 \
+	XDG_RUNTIME_DIR=/run/user/1000 \
 	DISPLAY=:0 \
 	DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus \
 	qdbus org.kde.plasmashell /PlasmaShell evaluateScript '
@@ -109,137 +109,134 @@ function update_refreshrate() {
 	if [[ "$scheduler" = "systemd" ]]; then
 		sed -i '/OnBootSec='"$active_refreshrate"'/!b;cOnBootSec='"$refreshrate" /home/"$usrnm"/.config/systemd/user/dynamicwall.timer.d/2-timer.conf
 		sed -i '/OnUnitActiveSec='"$active_refreshrate"'/!b;cOnUnitActiveSec='"$refreshrate" /home/"$usrnm"/.config/systemd/user/dynamicwall.timer.d/2-timer.conf
-    echo "$refreshrate" > "$oldvar_dir"/.active_refreshrate
-    notisend "Refresh rate updated, reloading systemd daemons" root
+		echo "$refreshrate" > "$oldvar_dir"/.active_refreshrate
+		notisend "Refresh rate updated, reloading systemd daemons" root
 		systemctl daemon-reload
 	elif [[ "$scheduler" = "cron" ]]; then
-    #Necessary loop to prompt user for password needed for crontab update until correct or skipped
-    wrongpass=0
-    while true; do
-      if ! sudo -n true; then
-        if [[ "$wrongpass" = 0 ]]; then
-          passwd=$(kdialog --title "Dynamic Wall" --password "Enter password to update crontab")
-        else
-          #Changes prompt when an incorrect password is entered
-          passwd=$(kdialog --title "Dynamic Wall" --password "Try Again")
-        fi
-      fi
-      if [[ "$?" = 0 ]]; then #Checks if ok or cancel was selected
-        echo "Selected: OK"
-        if echo "$passwd" | sudo -Svp ''; then
-          echo "correct password"
-          if [[ "$refreshrate" == [[:xdigit:]][[:xdigit:]][m] ]] || [[ "$refreshrate" == [[:xdigit:]][m] ]]; then
-            refreshrate_c=${refreshrate%?}
-            echo "$passwd" | sudo sh -c 'crontab -u '"$usrnm"' -l | grep -v "/home/'"$usrnm"'/bin/dynamic-wall/dynamicwall"  | crontab -u '"$usrnm"' - && crontab -u '"$usrnm"' -l | { cat; echo "*/'"$refreshrate_c"' * * * * /home/'"$usrnm"'/bin/dynamic-wall/dynamicwall"; } | crontab -u '"$usrnm"' -'
-          elif [[ "$refreshrate" == [[:xdigit:]][[:xdigit:]][h] ]] || [[ "$refreshrate" == [[:xdigit:]][h] ]]; then
-            refreshrate_c=${refreshrate%?}
-            echo "$passwd" | sudo sh -c 'crontab -u '"$usrnm"' -l | grep -v "/home/'"$usrnm"'/bin/dynamic-wall/dynamicwall"  | crontab -u '"$usrnm"' - && crontab -u '"$usrnm"' -l | { cat; echo "* */'"$refreshrate_c"' * * * /home/'"$usrnm"'/bin/dynamic-wall/dynamicwall"; } | crontab -u '"$usrnm"' -'
-          fi
-          echo "$refreshrate" > "$oldvar_dir"/.active_refreshrate
-          notisend "Refresh rate updated, crontab refreshed" root
-          break
-        else
-          echo "Wrong Password entered"
-          wrongpass=1
-        fi
-      else
-        echo "Selected: Cancel"
-        echo "Skipped"
-        break
-      fi
-    done
+		#Necessary loop to prompt user for password needed for crontab update until correct or skipped
+		wrongpass=0
+		while true; do
+			if ! sudo -n true; then
+				if [[ "$wrongpass" = 0 ]]; then
+					passwd=$(kdialog --title "Dynamic Wall" --password "Enter password to update crontab")
+				else
+					#Changes prompt when an incorrect password is entered
+					passwd=$(kdialog --title "Dynamic Wall" --password "Try Again")
+				fi
+			fi
+			if [[ "$?" = 0 ]]; then #Checks if ok or cancel was selected
+				echo "Selected: OK"
+				if echo "$passwd" | sudo -Svp ''; then
+					echo "correct password"
+					if [[ "$refreshrate" == [[:xdigit:]][[:xdigit:]][m] ]] || [[ "$refreshrate" == [[:xdigit:]][m] ]]; then
+						refreshrate_c=${refreshrate%?}
+						echo "$passwd" | sudo sh -c 'crontab -u '"$usrnm"' -l | grep -v "/home/'"$usrnm"'/bin/dynamic-wall/dynamicwall"  | crontab -u '"$usrnm"' - && crontab -u '"$usrnm"' -l | { cat; echo "*/'"$refreshrate_c"' * * * * /home/'"$usrnm"'/bin/dynamic-wall/dynamicwall"; } | crontab -u '"$usrnm"' -'
+					elif [[ "$refreshrate" == [[:xdigit:]][[:xdigit:]][h] ]] || [[ "$refreshrate" == [[:xdigit:]][h] ]]; then
+						refreshrate_c=${refreshrate%?}
+						echo "$passwd" | sudo sh -c 'crontab -u '"$usrnm"' -l | grep -v "/home/'"$usrnm"'/bin/dynamic-wall/dynamicwall"  | crontab -u '"$usrnm"' - && crontab -u '"$usrnm"' -l | { cat; echo "* */'"$refreshrate_c"' * * * /home/'"$usrnm"'/bin/dynamic-wall/dynamicwall"; } | crontab -u '"$usrnm"' -'
+					fi
+					echo "$refreshrate" > "$oldvar_dir"/.active_refreshrate
+					notisend "Refresh rate updated, crontab refreshed" root
+					break
+				else
+					echo "Wrong Password entered"
+					wrongpass=1
+				fi
+			else
+				echo "Selected: Cancel"
+				echo "Skipped"
+				break
+			fi
+		done
 	else
-    notisend "Uknown scheduler set in config file, not updating refreshrate..." root
+		notisend "Uknown scheduler set in config file, not updating refreshrate..." root
 	fi
 }
 
 function update_theme() {
 	echo "$cur_theme" > "$oldvar_dir"/.active_theme
-  notisend "Theme updated to $cur_theme" root
+	notisend "Theme updated to $cur_theme" root
 	active_theme=$cur_theme
 }
 
 function update_timeoffset() {
-		echo "$timeoffset" > "$oldvar_dir"/.active_timeoffset
-    notisend "Time offset updated to $timeoffset" root
+	echo "$timeoffset" > "$oldvar_dir"/.active_timeoffset
+	notisend "Time offset updated to $timeoffset" root
 }
 
 function find_theme() {
-		if ls -1 "$theme_dir"/"$1"/"$1"* > /dev/null 2>&1; then
-      filedir=$(basename "$(find "$theme_dir" -name "$1*" -type f | tail -1)")
-      ext=${filedir##*.}
-      case $ext in
-        jpg | jpeg )
-          return 0
-          ;;
-        png )
-          return 0
-          ;;
-        * )
-          echo "Incompatible image type($ext), exiting..."
-          return 1
-          exit
-          ;;
-      esac
-    else
-      ((++attempts))
-      echo ""
-      echo "Attempt $attempts"
-      if [[ $attempts = 1 ]]; then
-        notisend "Could not find $1, attempting to recover..." root
-        printf "Your theme_dir may not be set correctly or your cur_theme may be mispelt, check your dynamicwall.config\\nAttempting to recover...\\n"
-
-        echo "Attempting to use default theme directory"
-        find_defaults "theme_dir" "$2"
-      elif [[ $attempts = 2 ]]; then
-        if [[ $p = "set" ]]; then
-          return 1
-        fi
-        echo "Could not find theme in default directory"
-        echo "Attempting to use default theme in users theme directory"
-        eval "$(grep "theme_dir" < /home/"$usrnm"/bin/dynamic-wall/dynamicwall.config)"
-        find_defaults "cur_theme" "$2"
-      elif [[ $attempts = 3 ]]; then
-        echo "Could not find default theme in users theme directory"
-        echo "Attempting to use default theme in default theme directory"
-        find_defaults "theme_dir" "$2"
-      else
-        echo "There are some major problems with your configuration, reinstall dynamicwall to fix your configuration files"
-        return 1
-      fi
+	if ls -1 "$theme_dir"/"$1"/"$1"* > /dev/null 2>&1; then
+		filedir=$(basename "$(find "$theme_dir" -name "$1*" -type f | tail -1)")
+		ext=${filedir##*.}
+		case $ext in
+			jpg | jpeg )
+				return 0
+				;;
+			png )
+				return 0
+				;;
+			* )
+				echo "Incompatible image type($ext), exiting..."
+				return 1
+				exit
+				;;
+		esac
+	else
+		((++attempts))
+		echo ""
+		echo "Attempt $attempts"
+		if [[ $attempts = 1 ]]; then
+			notisend "Could not find $1, attempting to recover..." root
+			printf "Your theme_dir may not be set correctly or your cur_theme may be mispelt, check your ynamicwall.config\\nAttempting to recover...\\n"
+			echo "Attempting to use default theme directory"
+			find_defaults "theme_dir" "$2"
+		elif [[ $attempts = 2 ]]; then
+			if [[ $p = "set" ]]; then
+				return 1
+			fi
+			echo "Could not find theme in default directory"
+			echo "Attempting to use default theme in users theme directory"
+			eval "$(grep "theme_dir" < /home/"$usrnm"/bin/dynamic-wall/dynamicwall.config)"
+			find_defaults "cur_theme" "$2"
+		elif [[ $attempts = 3 ]]; then
+			echo "Could not find default theme in users theme directory"
+			echo "Attempting to use default theme in default theme directory"
+			find_defaults "theme_dir" "$2"
+		else
+			echo "There are some major problems with your configuration, reinstall dynamicwall to fix your configuration files"
+			return 1
 		fi
+	fi
 }
 
 function find_defaults() {
 	if ! [[ -f /home/$usrnm/bin/dynamic-wall/default.config ]]; then
-    echo "Can't find default config file, exiting..."
-    exit
-  fi
-
-  eval "$(grep "$1" < /home/"$usrnm"/bin/dynamic-wall/default.config)"
-  if [[ $2 = "p" ]]; then
-    echo "p is set"
-    find_theme "$previewtheme" &&\
-  	if [[ $? = 1 ]]; then
+		echo "Can't find default config file, exiting..."
+		exit
+	fi
+	eval "$(grep "$1" < /home/"$usrnm"/bin/dynamic-wall/default.config)"
+	if [[ $2 = "p" ]]; then
+		echo "p is set"
+		find_theme "$previewtheme" &&\
+		if [[ $? = 1 ]]; then
   		echo "Can't locate default theme directory, exiting..."
   		exit
-  	fi
-  else
-    find_theme "$cur_theme" &&\
-  	if [[ $? = 1 ]]; then
+		fi
+	else
+		find_theme "$cur_theme" &&\
+		if [[ $? = 1 ]]; then
   		echo "Can't locate default theme directory, exiting..."
   		exit
-  	fi
-  fi
-
+		fi
+	fi
 }
 
 # Checks if timeoffset is a number and then if it is range
 if ! [ "$timeoffset" -eq "$timeoffset" ] 2> /dev/null; then
-  notisend "Invalid Time Offset($timeoffset), falling back to default.config" root
+	notisend "Invalid Time Offset($timeoffset), falling back to default.config" root
 	find_defaults "timeoffset=[[:digit:]]"
 elif ! [[ "$timeoffset" -le "23" && "$timeoffset" -ge "-23" ]]; then
-  notisend "Time Offset is out of range($timeoffset), falling back to default.config" root
+	notisend "Time Offset is out of range($timeoffset), falling back to default.config" root
 	find_defaults "timeoffset=[[:digit:]]"
 elif [[ $((date + timeoffset)) -gt 24 ]]; then
 	date=$((date - 24 + timeoffset))
@@ -255,12 +252,12 @@ find_theme "$cur_theme"
 # Checks if refreshrate is in a valid format
 if ! [[ "$refreshrate" == [[:xdigit:]][[:xdigit:]][mh] ]] && ! [[ "$refreshrate" == [[:xdigit:]][mh] ]]; then
 	echo "Refresh rate is invalid, loading default.config"
-  notisend "Invalid Refresh Rate($refreshrate), falling back to default.config" root
+	notisend "Invalid Refresh Rate($refreshrate), falling back to default.config" root
 	find_defaults "refreshrate=[[:digit:]]"
   #check defaults
   if ! [[ "$refreshrate" == [[:xdigit:]][[:xdigit:]][mh] ]] && ! [[ "$refreshrate" == [[:xdigit:]][mh] ]]; then
   	echo "Refresh rate is invalid, loading default.config"
-    notisend "Invalid Refresh Rate($refreshrate), your defaults are messed up" root
+		notisend "Invalid Refresh Rate($refreshrate), your defaults are messed up" root
   	exit
   fi
 fi
@@ -268,11 +265,11 @@ fi
 # Checks if date is a number and then if its in a valid range
 if ! [ $date -eq $date ] 2> /dev/null; then
 	echo "Date returning invalid value, loading default.config"
-  notisend "Invalid date($date), falling back to default.config" root
+	notisend "Invalid date($date), falling back to default.config" root
 	date=$(date +%H | sed 's/\<0//g')
 elif ! [[ "$date" -le "24" && "$date" -ge "0" ]]; then
 	echo "Date is out of range, this shouldn't happen... loading default.config"
-  notisend "Date is out of range($date), falling back to default.config" root
+	notisend "Date is out of range($date), falling back to default.config" root
 	date=$(date +%H | sed 's/\<0//g')
 fi
 
@@ -288,7 +285,7 @@ if [[ $1 = "--preview" ]] || [[ $1 = "-p" ]]; then
 		if [[ $? = 0 ]]; then
 			active_theme=$2
 		else
-      notisend "Couldn't find $2, exiting..." manual
+			notisend "Couldn't find $2, exiting..." manual
 			echo "Couldn't find $2, exiting..."
 			exit
 		fi
@@ -296,7 +293,7 @@ if [[ $1 = "--preview" ]] || [[ $1 = "-p" ]]; then
 		dbusRef=$(kdialog --progressbar "Previewing" 20)
 		qdbus $dbusRef showCancelButton true
 		for (( date = 3; date < 24; date++ )); do
-      date +"%l:%M %p" -d $date
+			date +"%l:%M %p" -d $date
 			main_script
 			sleep 1.5
 			inc=$((`qdbus $dbusRef Get "" "value"` + 1))
@@ -308,10 +305,10 @@ if [[ $1 = "--preview" ]] || [[ $1 = "-p" ]]; then
 		done
 		qdbus $dbusRef close
 		echo "Preview Complete, reverting to normal..."
-    notisend "Reverting to normal..." manual
+		notisend "Reverting to normal..." manual
 		date=$olddate
 		active_theme=$cur_theme
-    find_theme "$active_theme"
+		find_theme "$active_theme"
 		main_script
 		exit
 	fi
