Replace --check with --config. Rework findtheme function. Correctly find default lock_theme. Correctly set variables in different places. offsetdate function added. Update config files with install_dir var. Update README.md

diff --git a/dynamic-wall/dynamicwall b/dynamic-wall/dynamicwall
--- a/dynamic-wall/dynamicwall
+++ b/dynamic-wall/dynamicwall
@@ -9,21 +9,14 @@ declare -A date
 date[real]=$(date +%H | sed 's/\<0//g')
 install_dir="/home/$usrnm/bin"
 scheduler=systemd
-# Source Config File
-source "$install_dir/dynamic-wall/dynamicwall.config" || { source "$install_dir/dynamic-wall/default.config"; notisend "Can't find user config files, loading defaults...";} || { notisend "Can't find user or default config files, exiting..."; exit 1; }
-date[desktop]=${date[real]}
-date[lockscreen]=${date[real]}
-# Get cached values
-oldvar_dir="$install_dir/dynamic-wall/.oldvar"
-source <(cat $oldvar_dir/*)
 
 HELP="\
 Usage: dynamicwall [OPTIONS]
 
 optional args:
   -f, --force [time]     Update wallpaper immediately, optionally to a specific time
-  -p, --preview <theme>  Run a 24 hour preview for a certain theme***EXPERIMENTAL***
-  -c, --check         	 Force check configuration options and push to script
+  -p, --preview <theme>  Run a 24 hour preview for a certain theme
+  -c, --config         	 Edit your config file using your default editor
   -s, --status           Display systemd service status/crontab and system-sleep script log
   -l, --list             List available themes to choose from
   -h, --help             Show help"
@@ -45,6 +38,20 @@ case $1 in
     fi
     exit 0
   ;;
+  --config | -c)
+    ${EDITOR:-nano} "$install_dir/dynamic-wall/dynamicwall.config"
+  ;;
+esac && if [[ -n $2 ]]; then echo "ignoring extra args..."; fi
+
+# Source Config File
+source "$install_dir/dynamic-wall/dynamicwall.config" || { source "$install_dir/dynamic-wall/default.config"; notisend "Can't find user config files, loading defaults...";} || { notisend "Can't find user or default config files, exiting..."; exit 1; }
+date[desktop]=${date[real]}
+date[lockscreen]=${date[real]}
+# Get cached values
+oldvar_dir="$install_dir/dynamic-wall/.oldvar"
+source <(cat $oldvar_dir/*)
+
+case $1 in
   --list | -l)
     echo "Available themes:"
     ls $theme_dir
@@ -54,24 +61,24 @@ esac && if [[ -n $2 ]]; then echo "ignoring extra args..."; fi
 
 #Determine image to use based on time
 function main_script() {
-  file=("$theme_dir/$active_theme/$active_theme" "$theme_dir/$lock_theme/$lock_theme")
+  file=("$theme_dir/$active_theme/$active_theme" "$theme_dir/$active_theme_lock/$active_theme_lock")
 	if [[ "${date[desktop]}" -le "4" || "${date[desktop]}" -gt "21" ]]; then
-    desktop="${file[0]}16.${ext[$cur_theme]}"
+    desktop="${file[0]}16.${ext[$active_theme]}"
 	elif [[ "${date[desktop]}" -le "9" ]]; then
-    desktop="${file[0]}$((date[desktop] - 4)).${ext[$cur_theme]}"
+    desktop="${file[0]}$((date[desktop] - 4)).${ext[$active_theme]}"
 	elif [[ "${date[desktop]}" -le "16" ]]; then
-    desktop="${file[0]}$((date[desktop] - 5)).${ext[$cur_theme]}"
+    desktop="${file[0]}$((date[desktop] - 5)).${ext[$active_theme]}"
 	elif [[ "${date[desktop]}" -le "21" ]]; then
-    desktop="${file[0]}$((date[desktop] - 6)).${ext[$cur_theme]}"
+    desktop="${file[0]}$((date[desktop] - 6)).${ext[$active_theme]}"
 	fi
   [[ -z $previewtheme ]] && if [[ "${date[lockscreen]}" -le "4" || "${date[lockscreen]}" -gt "21" ]]; then
-    lockscreen="${file[1]}16.${ext[$lock_theme]}"
+    lockscreen="${file[1]}16.${ext[$active_theme_lock]}"
 	elif [[ "${date[lockscreen]}" -le "9" ]]; then
-    lockscreen="${file[1]}$((date[lockscreen] - 4)).${ext[$lock_theme]}"
+    lockscreen="${file[1]}$((date[lockscreen] - 4)).${ext[$active_theme_lock]}"
 	elif [[ "${date[lockscreen]}" -le "16" ]]; then
-    lockscreen="${file[1]}$((date[lockscreen] - 5)).${ext[$lock_theme]}"
+    lockscreen="${file[1]}$((date[lockscreen] - 5)).${ext[$active_theme_lock]}"
 	elif [[ "${date[lockscreen]}" -le "21" ]]; then
-    lockscreen="${file[1]}$((date[lockscreen] - 6)).${ext[$lock_theme]}"
+    lockscreen="${file[1]}$((date[lockscreen] - 6)).${ext[$active_theme_lock]}"
 	fi
   set_wallpaper
 	echo "olddate=${date[desktop]}" > "$oldvar_dir/olddate"
@@ -205,10 +212,22 @@ function update_timeoffset() {
 	echo "active_timeoffset=$timeoffset" > "$oldvar_dir/active_timeoffset"
   echo "active_timeoffset_lock=$lock_timeoffset" > "$oldvar_dir/active_timeoffset_lock"
 	notisend "Desktop time offset updated to $timeoffset, Lockscreen time offset updated to $lock_timeoffset"
+  active_timeoffset=$timeoffset
+  active_timeoffset_lock=$lock_timeoffset
+}
+
+offsetdate(){
+  if [[ $((date[real] + $2)) -gt 24 ]]; then
+    date[$1]=$((date[real] - 24 + $2))
+  elif [[ $((date[real] + $2)) -lt 0 ]]; then
+    date[$1]=$((date[real] + 24 + $2))
+  else
+    date[$1]=$((date[real] + $2))
+  fi
 }
 
 function load_overrides() {
-	if . "$theme_dir/$cur_theme/override.config" 2> /dev/null
+	if source "$theme_dir/$cur_theme/override.config" 2> /dev/null
 	then
     if trueorfalse $printvariables; then
       echo "Loading variable overrides from override.config for $cur_theme"
@@ -220,27 +239,28 @@ function load_overrides() {
 }
 
 function find_theme() {
-	if [[ $2 = "skipcheck" ]] || find "$theme_dir/$1/$1"* > /dev/null 2>&1; then
-		filedir=$(basename "$(find "$theme_dir" -name "$1*" -type f | tail -1)")
-		ext[$1]=${filedir##*.}
-		case ${ext[$1]} in
+	if [[ $2 = "skipcheck" ]] || find "$theme_dir/${!1}/${!1}"* > /dev/null 2>&1; then
+		filedir=$(basename "$(find "$theme_dir" -name "${!1}*" -type f | tail -1)")
+		ext[${!1}]=${filedir##*.}
+		case ${ext[${!1}]} in
 			jpg | jpeg | png )
 				if [[ $2 != defaults ]]; then
-					load_overrides $1
+					load_overrides ${!1}
 				fi
+        [[ -n $attempts ]] && echo "Successfully loaded default theme ${!1} for $1"
 				return 0
 				;;
 			* )
-				echo "Incompatible image type(${ext[$1]}), exiting..."
+				echo "Incompatible image type(${ext[${!1}]}), exiting..."
 				exit 1
 				;;
 		esac
 	else
 		((++attempts))
-		echo "\nAttempt $attempts"
+		printf "\nAttempt $attempts\n"
 		if [[ $attempts = 1 ]]; then
-			notisend "Could not find $1, attempting to recover..."
-			printf "Your theme_dir may not be set correctly or your cur_theme may be mispelt, check your dynamicwall.config"
+			notisend "Could not find ${!1}, attempting to recover..."
+			echo "Your theme_dir may not be set correctly or your $1 may be mispelt, check your dynamicwall.config"
 			echo "Attempting to use default theme directory"
 			find_defaults "theme_dir" "$2"
 		elif [[ $attempts = 2 ]]; then
@@ -250,7 +270,7 @@ function find_theme() {
 			echo "Could not find theme in default directory"
 			echo "Attempting to use default theme in users theme directory"
 			eval "$(grep "theme_dir" < "$install_dir/dynamic-wall/dynamicwall.config")"
-			find_defaults "cur_theme" "$2"
+			find_defaults "$1" "$2"
 		elif [[ $attempts = 3 ]]; then
 			echo "Could not find default theme in users theme directory"
 			echo "Attempting to use default theme in default theme directory"
@@ -270,24 +290,30 @@ function find_defaults() {
 	fi
 	eval "$(grep "$1" < "$install_dir/dynamic-wall/default.config")"
   notisend "loaded $(grep "$1" < "$install_dir/dynamic-wall/default.config")"
-  if [[ $1 = "theme_dir" ]] || [[ $1 = "cur_theme" ]]; then
+  if [[ $1 = "theme_dir" ]] || [[ $1 = "cur_theme" ]] || [[ $1 = "lock_theme" ]]; then
   	if [[ $2 = "preview" ]]; then
-  		find_theme "$previewtheme" defaults preview
+  		find_theme "previewtheme" defaults preview
       return $?
   	elif [[ "$cur_theme" != "$active_theme" ]]; then
-  		if ! find_theme "$cur_theme" defaults; then
+  		if ! find_theme "cur_theme" defaults; then
     		echo "Can't locate $cur_theme in default theme directory, exiting..."
     		exit 1
   		fi
       active_theme="$cur_theme"
+    elif [[ "$lock_theme" != "$active_theme_lock" ]]; then
+  		if ! find_theme "lock_theme" defaults; then
+    		echo "Can't locate $lock_theme in default theme directory, exiting..."
+    		exit 1
+  		fi
+      active_theme_lock="$lock_theme"
   	fi
   fi
 }
 
 # Checks if users current theme exist
 declare -A ext
-[[ "$active_theme" != "$cur_theme" ]] && find_theme "$cur_theme" || find_theme "$cur_theme" skipcheck
-[[ "$active_theme_lock" != "$lock_theme" ]] && find_theme "$lock_theme" || find_theme "$lock_theme" skipcheck
+[[ "$active_theme" != "$cur_theme" ]] && find_theme "cur_theme" || find_theme "cur_theme" skipcheck
+[[ "$active_theme_lock" != "$lock_theme" ]] && find_theme "lock_theme" || find_theme "lock_theme" skipcheck
 
 # Checks if timeoffset is a number and then if it is range and checks if refreshrate is in a valid format
 if [[ "$active_timeoffset" != "$timeoffset" ]] || [[ "$active_timeoffset_lock" != "$lock_timeoffset" ]]; then
@@ -300,15 +326,8 @@ if [[ "$active_timeoffset" != "$timeoffset" ]] || [[ "$active_timeoffset_lock" !
       if ! [[ "$timeoffset" -le "23" && "$timeoffset" -ge "-23" ]]; then
       	notisend "Time Offset is out of range($timeoffset), loading defaults..."
       	find_defaults "timeoffset=[[:digit:]]"
-      elif [[ $((date[real] + timeoffset)) -gt 24 ]]; then
-      	date[desktop]=$((date[real] - 24 + timeoffset))
-        valid1=true
-      elif [[ $((date[real] + timeoffset)) -lt 0 ]]; then
-      	date[desktop]=$((date[real] + 24 + timeoffset))
-        valid1=true
       else
-      	date[desktop]=$((date[real] + timeoffset))
-        valid1=true
+        offsetdate desktop timeoffset && valid1=true
       fi
     fi
   done
@@ -322,33 +341,14 @@ if [[ "$active_timeoffset" != "$timeoffset" ]] || [[ "$active_timeoffset_lock" !
       if ! [[ "$lock_timeoffset" -le "23" && "$lock_timeoffset" -ge "-23" ]]; then
       	notisend "Time Offset is out of range($lock_timeoffset), loading defaults..."
       	find_defaults "lock_timeoffset=[[:digit:]]"
-      elif [[ $((date[real] + lock_timeoffset)) -gt 24 ]]; then
-      	date[lockscreen]=$((date[real] - 24 + lock_timeoffset))
-        valid3=true
-      elif [[ $((date[real] + lock_timeoffset)) -lt 0 ]]; then
-      	date[lockscreen]=$((date[real] + 24 + lock_timeoffset))
-        valid3=true
       else
-      	date[lockscreen]=$((date[real] + lock_timeoffset))
-        valid3=true
+        offsetdate lockscreen lock_timeoffset && valid3=true
       fi
     fi
   done
 else
-  if [[ $((date[real] + timeoffset)) -gt 24 ]]; then
-    date[desktop]=$((date[real] - 24 + timeoffset))
-  elif [[ $((date[real] + timeoffset)) -lt 0 ]]; then
-    date[desktop]=$((date[real] + 24 + timeoffset))
-  else
-    date[desktop]=$((date[real] + timeoffset))
-  fi
-  if [[ $((date[real] + lock_timeoffset)) -gt 24 ]]; then
-    date[lockscreen]=$((date[real] - 24 + lock_timeoffset))
-  elif [[ $((date[real] + lock_timeoffset)) -lt 0 ]]; then
-    date[lockscreen]=$((date[real] + 24 + lock_timeoffset))
-  else
-    date[lockscreen]=$((date[real] + lock_timeoffset))
-  fi
+  offsetdate desktop timeoffset
+  offsetdate lockscreen lock_timeoffset
 fi
 
 [[ $active_refreshrate != "$refreshrate" ]] && {
@@ -386,7 +386,7 @@ case $1 in
       printf "no theme selected to preview\\nusage: dynamicwall [--preview] <theme>\\n"
       exit 1
     else
-      if ! find_theme "$previewtheme" preview; then
+      if ! find_theme "previewtheme" preview; then
         notisend "Couldn't find $previewtheme, exiting..."
         exit 1
       fi
@@ -402,7 +402,7 @@ case $1 in
       notisend "Preview complete, reverting to normal..."
       date[desktop]=$olddate
       active_theme="$cur_theme"
-      find_theme "$active_theme"
+      find_theme "cur_theme"
       main_script
       exit 0
     fi
@@ -421,18 +421,6 @@ case $1 in
     fi
     main_script
     echo "Forced script to run, ignoring config changes"
-    exit 0
-  ;;
-  --check | -c )
-    if [[ -n $2 ]]; then
-      echo "Incompatible arguments, use one at a time, exiting..."
-      exit 1
-    fi
-    update_refreshrate
-    update_theme
-    update_timeoffset
-    main_script
-    echo "Updated config and forced run"
     exit 0
   ;;
 esac && if [[ -n $3 ]]; then echo "Ignoring extra args..."; fi
